name: AlgDat_Damen
version: '1.0-SNAPSHOT'
main: de.hsmw.algDatDamen.AlgDatDamen
api-version: '1.21'
commands:
  schachmenu:
    description: 'Öffnet das Schachmenü'
    usage: '/schachmenu'
    aliases: [sm, cb]